### ISSUE TITLE
Having an issue with PostgreSQL and TeslaMate.Log.get_positions_without_elevation

### ISSUE THREAD

**Issue by marval** [teslamate-org/teslamate#3555]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

First of all let me state that I believe this is more of a data error, but nevertheless it takes my whole docker setup down. I believe there is something wrong with my "positions" table. 

A bit of background:
- I am using Teslamate for two vehicles if that has any impact.
- I originally installed Teslamate back in december 2021 and have not been upgrading each version but more like ... once every 6 months or so.
- I have recently upgraded

Running some COUNTs on the table I can see a lot of drives (14325810) that fulfill the "|> filter(not is_nil(p.odometer) and is_nil(p.ideal_battery_range_km))" criteria. I am assuming there are so many that this query times out.

What happens is that all my docker applications become so slow/unresponsive/unusable.

### Relevant log output

```shell
2023-12-08 17:07:19.408 [error] GenStateMachine TeslaMate.Terrain terminating
** (DBConnection.ConnectionError) tcp recv: closed (the connection was closed by the pool, possibly due to a timeout or because the pool has been terminated)
    (ecto_sql 3.10.2) lib/ecto/adapters/sql.ex:1047: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto_sql 3.10.2) lib/ecto/adapters/sql.ex:945: Ecto.Adapters.SQL.execute/6
    (ecto 3.10.3) lib/ecto/repo/queryable.ex:229: Ecto.Repo.Queryable.execute/4
    (ecto 3.10.3) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
    (teslamate 1.28.2) lib/teslamate/log.ex:177: TeslaMate.Log.get_positions_without_elevation/2
    (teslamate 1.28.2) lib/teslamate/terrain.ex:77: TeslaMate.Terrain.handle_event/4
    (stdlib 5.1.1) gen_statem.erl:1379: :gen_statem.loop_state_callback/11
    (stdlib 5.1.1) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
```

### Type of installation

Docker

### Version

v 1.28.2

**Comment by JakobLichterfeld** [comment]
Hi Marval,

thanks for reporting. I would suggest you do a full backup and start with a fresh installation with latest Postgres etc. The Migration will hopefully resolve your issues.

**Comment by marval** [comment]
Hi @JakobLichterfeld,

thanks for your reply. This is kind of what I did and it seems that the issue has been fixed. Wanted to give it a week before I close it.

**Comment by kahobusiness** [comment]
Excuse me, but how can I do a full backup for my Teslamate data? 

I have followed this documentation [https://docs.teslamate.org/docs/maintenance/backup_restore/](https://docs.teslamate.org/docs/maintenance/backup_restore/) to make a backup and restore it to a fresh new NAS with TeslaMate. All the data seems to have moved okay - I can see all my old data in the dashboards.However, the map visualisation on the "Visited" dashboard which shows locations visited on a map has lost all the history. It's only got locations visited since I moved the data.

I think there is something wrong with my "positions" table too...

**Comment by hugoduraes** [comment]
@JakobLichterfeld I'm having the same issue as @marval. Following your suggestion, I've backed up the data, upgraded Postgres from 13 to 15 and restored the backup. However, the issue persists!
I'm getting this on teslamate container logs:

```
teslamate  | 2024-01-09 11:29:37.767 [error] GenStateMachine TeslaMate.Terrain terminating
teslamate  | ** (DBConnection.ConnectionError) tcp recv: closed (the connection was closed by the pool, possibly due to a timeout or because the pool has been terminated)
teslamate  |     (ecto_sql 3.10.2) lib/ecto/adapters/sql.ex:1047: Ecto.Adapters.SQL.raise_sql_call_error/1
teslamate  |     (ecto_sql 3.10.2) lib/ecto/adapters/sql.ex:945: Ecto.Adapters.SQL.execute/6
teslamate  |     (ecto 3.10.3) lib/ecto/repo/queryable.ex:229: Ecto.Repo.Queryable.execute/4
teslamate  |     (ecto 3.10.3) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
teslamate  |     (teslamate 1.28.2) lib/teslamate/log.ex:197: TeslaMate.Log.get_positions_without_elevation/2
teslamate  |     (teslamate 1.28.2) lib/teslamate/terrain.ex:77: TeslaMate.Terrain.handle_event/4
teslamate  |     (stdlib 5.1.1) gen_statem.erl:1379: :gen_statem.loop_state_callback/11
teslamate  |     (stdlib 5.1.1) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
teslamate  | 2024-01-09 11:31:08.238 [error] Postgrex.Protocol (#PID<0.2430.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.2689.0> timed out because it queued and checked out the connection for longer than 60000ms
teslamate  |
teslamate  | #PID<0.2689.0> was at location:
teslamate  |
teslamate  |     :prim_inet.recv0/3
teslamate  |     (postgrex 0.17.3) lib/postgrex/protocol.ex:3188: Postgrex.Protocol.msg_recv/4
teslamate  |     (postgrex 0.17.3) lib/postgrex/protocol.ex:2213: Postgrex.Protocol.recv_bind/3
teslamate  |     (postgrex 0.17.3) lib/postgrex/protocol.ex:2105: Postgrex.Protocol.bind_execute/4
teslamate  |     (db_connection 2.6.0) lib/db_connection/holder.ex:354: DBConnection.Holder.holder_apply/4
teslamate  |     (db_connection 2.6.0) lib/db_connection.ex:1512: DBConnection.run_execute/5
teslamate  |     (db_connection 2.6.0) lib/db_connection.ex:1607: DBConnection.run/6
teslamate  |     (db_connection 2.6.0) lib/db_connection.ex:743: DBConnection.parsed_prepare_execute/5
```

And this on the teslamate database container logs:

```
teslamate-database  | 2024-01-09 11:35:41.333 UTC [164] ERROR:  canceling statement due to user request
teslamate-database  | 2024-01-09 11:35:41.333 UTC [164] STATEMENT:  SELECT p0."id", p0."date", p0."latitude", p0."longitude", p0."elevation", p0."speed", p0."power", p0."odometer", p0."ideal_battery_range_km", p0."est_battery_range_km", p0."rated_battery_range_km", p0."battery_level", p0."usable_battery_level", p0."battery_heater", p0."battery_heater_on", p0."battery_heater_no_power", p0."outside_temp", p0."inside_temp", p0."fan_status", p0."driver_temp_setting", p0."passenger_temp_setting", p0."is_climate_on", p0."is_rear_defroster_on", p0."is_front_defroster_on", p0."tpms_pressure_fl", p0."tpms_pressure_fr", p0."tpms_pressure_rl", p0."tpms_pressure_rr", p0."car_id", p0."drive_id" FROM "positions" AS p0 WHERE (((p0."id" > $1) AND (p0."elevation" IS NULL)) AND p0."drive_id" = ANY($2)) ORDER BY p0."id" LIMIT $3
teslamate-database  | 2024-01-09 11:35:41.380 UTC [305] FATAL:  terminating background worker "parallel worker" due to administrator command
teslamate-database  | 2024-01-09 11:35:41.380 UTC [305] STATEMENT:  SELECT p0."id", p0."date", p0."latitude", p0."longitude", p0."elevation", p0."speed", p0."power", p0."odometer", p0."ideal_battery_range_km", p0."est_battery_range_km", p0."rated_battery_range_km", p0."battery_level", p0."usable_battery_level", p0."battery_heater", p0."battery_heater_on", p0."battery_heater_no_power", p0."outside_temp", p0."inside_temp", p0."fan_status", p0."driver_temp_setting", p0."passenger_temp_setting", p0."is_climate_on", p0."is_rear_defroster_on", p0."is_front_defroster_on", p0."tpms_pressure_fl", p0."tpms_pressure_fr", p0."tpms_pressure_rl", p0."tpms_pressure_rr", p0."car_id", p0."drive_id" FROM "positions" AS p0 WHERE (((p0."id" > $1) AND (p0."elevation" IS NULL)) AND p0."drive_id" = ANY($2)) ORDER BY p0."id" LIMIT $3
teslamate-database  | 2024-01-09 11:35:41.389 UTC [306] FATAL:  terminating background worker "parallel worker" due to administrator command
teslamate-database  | 2024-01-09 11:35:41.389 UTC [306] STATEMENT:  SELECT p0."id", p0."date", p0."latitude", p0."longitude", p0."elevation", p0."speed", p0."power", p0."odometer", p0."ideal_battery_range_km", p0."est_battery_range_km", p0."rated_battery_range_km", p0."battery_level", p0."usable_battery_level", p0."battery_heater", p0."battery_heater_on", p0."battery_heater_no_power", p0."outside_temp", p0."inside_temp", p0."fan_status", p0."driver_temp_setting", p0."passenger_temp_setting", p0."is_climate_on", p0."is_rear_defroster_on", p0."is_front_defroster_on", p0."tpms_pressure_fl", p0."tpms_pressure_fr", p0."tpms_pressure_rl", p0."tpms_pressure_rr", p0."car_id", p0."drive_id" FROM "positions" AS p0 WHERE (((p0."id" > $1) AND (p0."elevation" IS NULL)) AND p0."drive_id" = ANY($2)) ORDER BY p0."id" LIMIT $3
teslamate-database  | 2024-01-09 11:35:41.403 UTC [1] LOG:  background worker "parallel worker" (PID 305) exited with exit code 1
teslamate-database  | 2024-01-09 11:35:41.411 UTC [1] LOG:  background worker "parallel worker" (PID 306) exited with exit code 1
teslamate-database  | 2024-01-09 11:35:41.412 UTC [164] LOG:  could not send data to client: Broken pipe
teslamate-database  | 2024-01-09 11:35:41.412 UTC [164] FATAL:  connection to client lost
```

Any hint on what may be the issue?

**Comment by JakobLichterfeld** [comment]
> @JakobLichterfeld I'm having the same issue as @marval. 
>Any hint on what may be the issue?

You don't. 
In your case, you need to set a proper value fortDATABASE_TIMEOUT, see: https://docs.teslamate.org/docs/configuration/environment_variables/

Please open a separate issue if it is not solved.
