### ISSUE TITLE
CI: update upload-artifact action

### ISSUE THREAD

**Issue by JakobLichterfeld** [teslamate-org/teslamate#3689]
Run output: https://github.com/teslamate-org/teslamate/actions/runs/8035109824

> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/upload-artifact@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

--> Update to upload-artifact@v4

[Breaking changes](https://github.com/actions/upload-artifact?tab=readme-ov-file#breaking-changes) --> see [Migration Guide](https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md)

**Comment by micves** [comment]
Think this is causing errors in:
https://github.com/teslamate-org/teslamate/actions/runs/8064800308/job/22029399915
> Error: Failed to CreateArtifact: Received non-retryable error: Failed request: (409) Conflict: an artifact with this name already exists on the workflow run

Found something here that could explain it:
https://github.com/actions/upload-artifact/issues/478

**Comment by JakobLichterfeld** [comment]
Thanks, GitHub Actions are hard to test locally (even if it is possible in most cases).
Will take a deeper look into the naming. I was aware of the breaking change and considered it as not relevant, as we use it differently.

**Comment by micves** [comment]
Thanks for looking into it. There are many small steps in CI at the moment, but at some point it's all going to be sorted out :)

**Comment by JakobLichterfeld** [comment]
fixed with https://github.com/teslamate-org/teslamate/commit/39ab647122dd9eb5b5a3a660be993e88e7c31ebb
Unfortunately not tested, as for security reasons changes in `.github`folder are excluded for our automatic ci

**Comment by micves** [comment]
It looks like it works on master, but still not on PRs :(
https://github.com/teslamate-org/teslamate/actions/runs/8082839912/job/22084555821

in the log it seems to ignore ${{ matrix.runs-on }}
> 2024-02-28T15:27:19.5466184Z ##[group]Run actions/upload-artifact@v4
> 2024-02-28T15:27:19.5466740Z with:
> 2024-02-28T15:27:19.5467093Z   name: single-digest-

**Comment by JakobLichterfeld** [comment]
Test with #3702

**Comment by JakobLichterfeld** [comment]
As I needed to adopt the digest naming again and our security is working, new test with #3703

**Comment by JakobLichterfeld** [comment]
Good think our security guards works perfectly. Bad thing: testing GitHub actions is now a pain.

**Comment by JakobLichterfeld** [comment]
Test with #3704

**Comment by JakobLichterfeld** [comment]
Ok test looks good for the upload now, the merging is still failing: https://github.com/teslamate-org/teslamate/actions/runs/8089110554/job/22104597849?pr=3485

**Comment by JakobLichterfeld** [comment]
new test for merging with #3705

**Comment by JakobLichterfeld** [comment]
merging works as expected, as path is not supported anymore, the working directory needs to be set beforehand

**Comment by JakobLichterfeld** [comment]
new test with #3706

**Comment by JakobLichterfeld** [comment]
Finally working with v4 action, https://github.com/teslamate-org/teslamate/actions/runs/8094659397?pr=3708

**Comment by micves** [comment]
Thanks a lot, that looks like it was a rough one :|
