### ISSUE TITLE
The Drive Details map doesn't zoom to fit after selecting a subset of the drive

### ISSUE THREAD

**Issue by dyxyl** [teslamate-org/teslamate#4664]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### What happened?

After upgrading from v1.32.0 to v1.33.0 (self built on FreeBSD 13.5), the map in the Drive Details dashboard has stopped zooming to fit after selecting a subset of the drive (e.g. by dragging on one of  the graphs). I am using grafana 11.6.0 and Firefox 128.8.0esr. It worked with v1.32.0 and grafana 11.2.5.

### Expected Behavior

The map should zoom to fit the selected part of the drive.

### Steps To Reproduce

1. Go to a Drive Details dashboard.
2. Drag a rectangle on the Drive graph to select that subset of the drive.
3. Notice that the map doesn't zoom in.  In fact, it sometimes zooms out a little.

### Relevant log output

```shell
2025-04-15 13:13:22.299 [info] System Info: Erlang/OTP 26 (jit)
2025-04-15 13:13:22.299 [info] Version: 1.33.0
2025-04-15 13:13:23.018 [info] POST https://auth.tesla.com/oauth2/v3/token -> 200 (590.997 ms)
2025-04-15 13:13:23.018 [info] Refreshed api tokens
2025-04-15 13:13:23.040 [info] Scheduling token refresh in 6 ?h
2025-04-15 13:13:23.051 [info] Running TeslaMateWeb.Endpoint with cowboy 2.13.0 at 127.0.0.1:4000 (http)
2025-04-15 13:13:23.054 [info] Access TeslaMateWeb.Endpoint at http://localhost
2025-04-15 13:13:23.597 [info] Starting logger for ''
2025-04-15 13:13:23.972 car_id=1 [info] Start / :online
2025-04-15 13:13:24.710 car_id=1 [info] Stream connecting ...
2025-04-15 13:13:49.637 [info] GET /
2025-04-15 13:13:49.641 [info] Sent 200 in 3ms
2025-04-15 13:16:27.273 car_id=1 [info] Suspending logging
```

### Type of installation

Manual

### Version

v1.33.0

### PostgreSQL version

17.4

### Are you running latest major supported PostgreSQL version?

- [x] I run the latest major supported PostgreSQL version

**Comment by JakobLichterfeld** [comment]
Thanks for reporting, I can reproduce it with our supported installation: https://docs.teslamate.org/docs/installation/docker/

@swiffer: Can you take a look in the fit to zoom issue? Sorry for bothering you so much lately.

**Comment by swiffer** [comment]
Grafana issue I guess - commented in the PR that attempted to fix fit to data

https://github.com/grafana/grafana/pull/101391#issuecomment-2817042603

**Comment by swiffer** [comment]
@dyxyl - workaround for now is pressing F5 once you have selected a subset of the drive

**Comment by swiffer** [comment]
This should have been fixed in one of the latest Grafana updates.

**Comment by dyxyl** [comment]
I'm still seeing this problem with v2.1.1 and grafana 12.1.0.

**Comment by JakobLichterfeld** [comment]
> I'm still seeing this problem with v2.1.1 and grafana 12.1.0.

Indeed reproducible, in my case it zooms out

**Comment by swiffer** [comment]
sorry, should have verified first - opened an issue upstream: https://github.com/grafana/grafana/issues/112009
